# version: "3.8"
services:
  backend:
    build:
      context: ./backend

    container_name: backend
    image: idb-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
      # - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    image: idb-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  sql: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'model'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'root'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'StormShelters2023'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'StormShelters2023'
    ports:
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./backend:/usr/src/app